---
- name: app instance setup
  hosts: app

  user: vagrant
  become: yes

  vars:
    - dbhost: "192.168.56.3"
    - dbname: "notes"
    - dbusername: "notesapps"
    - dbpassword: "devopslabs"
  tasks:
    - name: lab hosts config
      lineinfile: 
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - 192.168.56.2 app01
        - 192.168.56.3 db01
    - name: add app user
      user:
        name: app
        comment: application user
        uid: 500
    - name: maven download
      get_url:
        url: https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.1.0/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/apache-maven-3.1.0-bin.tar.gz
    - name: unzip maven package
      ansible.builtin.unarchive:
        src: /opt/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/
        remote_src: yes
    - name: java 1.8 install
      yum:
        name: java-1.8.0-openjdk
        state: latest
    - name: app directiories creation
      file:
        path: /opt/notes
        state: directory
        owner: app
        group: app
    - name: git client install
      yum:
        name: git
        state: latest
    - name: source code repo clone
      git:
        repo: 'https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git'
        dest: /opt/notes
        clone: yes
        force: yes
    - name: pom.xml file setup for the db slice
      template:
        src: pom.xml
        dest: /opt/notes/pom.xml
    - name: property file setup for the db slice
      template:
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties
    - name: generate application packages
      command: /opt/apache-maven-3.1.0/bin/mvn -f /opt/notes/pom.xml package
      become_user: app
    - name: package latest version register
      shell:
        cmd: mvn -o -q -Dexec.executable=echo -Dexec.args='${project.version}'
        chdir: /opt/notes/
      register: app_version
    - name: systemd service config
      template:
        src: etc/systemd/system/note.service
        src: /etc/systemd/system/notes.service
        notify: reload daemon
    - name: service notes start
      service:
        name: notes
        state: restarted
  roles:
    - so-default-config
  handlers:
    - name: reload app
      systemd:
        state: restarted
        daemon_reload: yes
        name: 'notes'
    - name: reload daemon
      systemd:
        daemon_reexec: yes