version: '3.7'

services:
  postgresql:
    image: postgres:14.10-alpine
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sonarqube
    network_mode: "host"
    volumes:
      - pgsql:/var/lib/postgresql
      - pgsql_data:/var/lib/postgresql/data

volumes:
  pgsql:
  pgsql_data: