# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.hostname = "db01"
  config.vm.box = "centos/7"

  config.vm.network "private_network", ip: "192.168.56.3"
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
end
